#!/bin/bash
# ESM2-3B Batch Processing Script for AMD MI300X
# Auto-generated by split_fasta_by_length.py

set -e

CONDA_ENV="amd_protein"
OUTPUT_DIR="embeddings_output"
MODEL="esm2_t36_3B_UR50D"

echo "=========================================="
echo "ESM2-3B Batch Processing on AMD MI300X"
echo "=========================================="
echo ""

# Create output directory
mkdir -p $OUTPUT_DIR

# Activate conda environment
eval "$(conda shell.bash hook)"
conda activate $CONDA_ENV


# Process bin1_0-99aa (3,257 sequences, batch size: 256)
echo "Processing bin1_0-99aa..."
echo "  Sequences: 3,257"
echo "  Batch size: 256"
echo "  Estimated time: 0.01 hours"

python esm2_inference.py \
    --input sequences_by_length/bin1_0-99aa/bin1_0-99aa.fasta \
    --output $OUTPUT_DIR/bin1_0-99aa_embeddings.pt \
    --model $MODEL \
    --batch-size 256 \
    --precision fp16 \
    --device cuda

echo "✓ Completed bin1_0-99aa"
echo ""


# Process bin2_100-199aa (12,634 sequences, batch size: 256)
echo "Processing bin2_100-199aa..."
echo "  Sequences: 12,634"
echo "  Batch size: 256"
echo "  Estimated time: 0.03 hours"

python esm2_inference.py \
    --input sequences_by_length/bin2_100-199aa/bin2_100-199aa.fasta \
    --output $OUTPUT_DIR/bin2_100-199aa_embeddings.pt \
    --model $MODEL \
    --batch-size 256 \
    --precision fp16 \
    --device cuda

echo "✓ Completed bin2_100-199aa"
echo ""


# Process bin3_200-299aa (11,222 sequences, batch size: 256)
echo "Processing bin3_200-299aa..."
echo "  Sequences: 11,222"
echo "  Batch size: 256"
echo "  Estimated time: 0.03 hours"

python esm2_inference.py \
    --input sequences_by_length/bin3_200-299aa/bin3_200-299aa.fasta \
    --output $OUTPUT_DIR/bin3_200-299aa_embeddings.pt \
    --model $MODEL \
    --batch-size 256 \
    --precision fp16 \
    --device cuda

echo "✓ Completed bin3_200-299aa"
echo ""


# Process bin4_300-399aa (12,094 sequences, batch size: 166)
echo "Processing bin4_300-399aa..."
echo "  Sequences: 12,094"
echo "  Batch size: 166"
echo "  Estimated time: 0.05 hours"

python esm2_inference.py \
    --input sequences_by_length/bin4_300-399aa/bin4_300-399aa.fasta \
    --output $OUTPUT_DIR/bin4_300-399aa_embeddings.pt \
    --model $MODEL \
    --batch-size 166 \
    --precision fp16 \
    --device cuda

echo "✓ Completed bin4_300-399aa"
echo ""


# Process bin5_400-499aa (10,124 sequences, batch size: 108)
echo "Processing bin5_400-499aa..."
echo "  Sequences: 10,124"
echo "  Batch size: 108"
echo "  Estimated time: 0.07 hours"

python esm2_inference.py \
    --input sequences_by_length/bin5_400-499aa/bin5_400-499aa.fasta \
    --output $OUTPUT_DIR/bin5_400-499aa_embeddings.pt \
    --model $MODEL \
    --batch-size 108 \
    --precision fp16 \
    --device cuda

echo "✓ Completed bin5_400-499aa"
echo ""


# Process bin6_500-999aa (24,076 sequences, batch size: 44)
echo "Processing bin6_500-999aa..."
echo "  Sequences: 24,076"
echo "  Batch size: 44"
echo "  Estimated time: 0.38 hours"

python esm2_inference.py \
    --input sequences_by_length/bin6_500-999aa/bin6_500-999aa.fasta \
    --output $OUTPUT_DIR/bin6_500-999aa_embeddings.pt \
    --model $MODEL \
    --batch-size 44 \
    --precision fp16 \
    --device cuda

echo "✓ Completed bin6_500-999aa"
echo ""


# Process bin7_1000-1999aa (6,386 sequences, batch size: 12)
echo "Processing bin7_1000-1999aa..."
echo "  Sequences: 6,386"
echo "  Batch size: 12"
echo "  Estimated time: 0.37 hours"

python esm2_inference.py \
    --input sequences_by_length/bin7_1000-1999aa/bin7_1000-1999aa.fasta \
    --output $OUTPUT_DIR/bin7_1000-1999aa_embeddings.pt \
    --model $MODEL \
    --batch-size 12 \
    --precision fp16 \
    --device cuda

echo "✓ Completed bin7_1000-1999aa"
echo ""


# Process bin8_2000plus_aa (581 sequences, batch size: 2)
echo "Processing bin8_2000plus_aa..."
echo "  Sequences: 581"
echo "  Batch size: 2"
echo "  Estimated time: 0.20 hours"

python esm2_inference.py \
    --input sequences_by_length/bin8_2000plus_aa/bin8_2000plus_aa.fasta \
    --output $OUTPUT_DIR/bin8_2000plus_aa_embeddings.pt \
    --model $MODEL \
    --batch-size 2 \
    --precision fp16 \
    --device cuda

echo "✓ Completed bin8_2000plus_aa"
echo ""


echo "=========================================="
echo "✅ ALL BATCHES COMPLETED"
echo "Total estimated time: 1.14 hours (0.05 days)"
echo "=========================================="
